/* Kontrolle-Modus: je Rolle 10 Knöpfe in der Reihenfolge einer typischen Kontrolle.
   Jeder Knopf zeigt auf einen Eintrag in quick.js (dort die volle, geprüfte Antwort mit Quellen).
   kurz  = der Satz zum Aussprechen, nur aus dem geprüften „say“ gekürzt – keine neue Rechtsaussage.
   dann  = was tun, wenn der Beamte darauf besteht (aus „why“ des Eintrags).
   law   = der eine tragende Paragraf; alle Normen stehen im Eintrag.
   stich = Stichwörter für „Stichwort sagen“ und den Test-Mithörmodus. Wortanfang zählt („durchsuch“ trifft „durchsuchen“);
           ein Leerzeichen am Ende verlangt das ganze Wort („pass “ trifft nicht „passiert“).
   nicht = optionale Ausschluss-Stämme (5. Element am Knopf, 3. am Extra): trifft einer, bleibt dieser Knopf zu –
           für Verneinung und anderen Sinn („Sie dürfen gern filmen“, „nicht aussteigen“, „pass auf“).
   Noch nicht anwaltlich geprüft. */
window.RB = window.RB || {};
window.RB.kontrolle = {
  roles: [["fahrer", "Fahrer", "Водитель"], ["beifahrer", "Beifahrer", "Пассажир"], ["fuss", "Zu Fuß", "Пешком"], ["filme", "Ich filme", "Снимаю"]],
  // Hinweis unter den Knöpfen einer Rolle (z. B. wenn ein Freund mitgenommen wird)
  hinweis: { filme: { de: "Frag: „Wohin bringen Sie ihn?“ Anwaltsnotdienst:", ru: "Спроси: „Wohin bringen Sie ihn?“ Дежурный адвокат:", tel: "+4971199889966", telText: "0711 998 899 66" } },
  buttons: {
    fahrer: [
      ["fahrer-papiere", "Papiere", "Документы", ["führerschein", "fahrzeugschein", "fahrzeugpapiere", "papiere", "zulassung", "ausweis", "personalausweis", "ihren lappen", "lappen dabei", "права ", "документ", "техпаспорт"]],
      ["fahrer-fragen", "Getrunken? Woher?", "Пил? Откуда?", ["getrunken", "wo kommen sie", "wo wollen sie", "wo fahren sie", "woher", "wohin", "alkohol", "drogen genommen", "medikamente", "getrunke ", "hingehen", "hinfahren", "geht s hin", "gehts hin", "konsumier", "gekifft", "gehört das fahrzeug", "gehört denn das fahrzeug", "gehört das auto", "gehört denn das auto", "gehört der wagen", "gehört denn der wagen", "ist das ihr auto", "ist das ihr fahrzeug", "ist das ihr wagen", "waffen ", "eine waffe", "verbotenes", "пил", "откуда", "куда едете"]],
      ["fahrer-pusten", "Pusten", "Дуть в трубку", ["pusten", "puste ", "atemalkohol", "alkoholtest", "atemtest", "blasen", "röhrchen", "alkomat", "reinpust", "röhrle", "hier rein posten", "тест на алкогол", "дуть", "дуйте", "дуньте", "дыхни", "дыхните", "алкотест", "трубк"], ["nicht pusten", "nicht zu pusten", "kein alkoholtest", "keinen alkoholtest"]],
      ["fahrer-drogenvortest", "Urin-, Drogentest", "Тест мочи, наркотики", ["urin", "wischtest", "drogentest", "drogenschnelltest", "speichel", "mit den augen", "augen ", "pupille", "auf einer linie", "meinem finger", "meinen finger", "finger nase", "zur nase", "wisch test", "auf dieser linie", "ferse an spitze", "моч", "мазок", "наркотест", "тест на наркотики", "слюн", "палец", "пальц"]],
      ["fahrer-blut", "Blutprobe", "Анализ крови", ["blutprobe", "blutentnahme", "blut abnehmen", "blutabnahme", "bluttest", "eben blut", "nehmen wir blut", "blut nehmen", "blut entnehmen", "ihnen blut", "blut abgenommen", "jetzt blut ", "wir nehmen blut", "кров", "кровь "]],
      ["fahrer-aussteigen", "Aussteigen", "Выйти из машины", ["aussteigen", "steigen sie", "raus aus dem", "aus dem fahrzeug", "aus dem auto", "aus dem wagen", "kommen sie raus", "steigen sie aus", "steigen sie bitte aus", "steigen sie bitte mal aus", "steigen sie bitte einmal aus", "steigen sie bitte kurz aus", "steigen sie mal aus", "steigen sie einmal aus", "steigen sie kurz aus", "steigen sie jetzt aus", "steigen sie sofort aus", "bitte aussteigen", "mal aussteigen", "einmal aussteigen", "kurz aussteigen", "jetzt aussteigen", "sofort aussteigen", "sie aussteigen", "alle aussteigen", "aussteigen und", "einmal raus bitte", "mal raus bitte", "выйти", "выйдите", "выходите", "из машины"], ["nicht aussteigen", "nicht aus ", "sitzen bleiben", "bleiben sie sitzen", "bleiben sie im", "im auto bleiben", "im fahrzeug bleiben", "im wagen bleiben"]],
      ["fahrer-kofferraum", "Kofferraum, Auto", "Багажник, машина", ["kofferraum", "handschuhfach", "durchsuch", "schauen uns das auto", "ins auto", "heckklappe", "багажник", "бардачок", "досмотр", "обыск"]],
      ["fahrer-handy", "Handy zeigen, entsperren", "Телефон показать", ["entsperr", "handy", "handy her", "pin ", "code ", "разблок", "пароль", "телефон"]],
      ["aufnahme-filmen-stoppen", "Filmen aufhören", "Прекратить съёмку", ["sie filmen", "aufnehm", "aufnahme", "ihre kamera", "kamera aus", "video aus", "handy runter", "fotografier", "keine fotos", "nicht filmen", "nicht mehr filmen", "auf zu filmen", "hören sie auf zu filmen", "aufhören zu filmen", "uns zu filmen", "mit dem filmen", "lassen sie das filmen", "unterlassen sie das filmen", "stellen sie das filmen", "filmen einstellen", "kein filmen", "filmen verboten", "filmen ist verboten", "filmen ist hier verboten", "filmen ist untersagt", "filmen ist nicht erlaubt", "filmen sie nicht", "sie filmen nicht", "sie filmen hier nicht", "wird nicht gefilmt", "снимать", "съёмк", "запись ", "прекратите сним", "опустите телефон"], ["dürfen gern filmen", "dürfen gerne filmen", "dürfen ruhig filmen", "dürfen sie gern", "dürfen sie gerne", "dürfen sie ruhig", "können gern filmen", "können gerne filmen", "können ruhig filmen", "filmen sie ruhig", "filmen sie gern", "filmen dürfen sie", "filmen ist erlaubt", "ihr gutes recht", "stört uns nicht", "nichts zu verbergen"]],
      ["fahrer-unterschrift", "Unterschreiben", "Подписать", ["unterschreib", "unterschrift", "подпис", "подпиш"]]
    ],
    beifahrer: [
      ["person-beifahrer-ausweis", "Ausweis vom Beifahrer", "Документ пассажира", ["ausweis", "personalausweis", "perso ", "personalien", "ausweisen", "wie heißen sie", "документ", "паспорт", "удостоверени", "посвідч"]],
      ["druck-zeuge-beifahrer", "Aussagen als Zeuge", "Показания свидетеля", ["zeuge", "aussage", "aussagen", "gefahren", "getrunken", "geraucht", "gekifft", "hat der fahrer", "getippt", "свидетел", "свідок", "показани", "за рулём", "кермо", "пил"]],
      ["person-grund", "Grund? „Normale Kontrolle“", "Причина?", ["grund ", "normale kontrolle", "allgemeine kontrolle", "verdachtsunabhängig", "reine routine", "weil wir das halt", "weil mir des halt", "причин", "обычная проверка"], ["grund ihres aufenthalt", "grund halten sie sich", "welchem grund halten"]],
      ["person-taschen-durchsuchen", "Taschen durchsuchen", "Обыск, карманы", ["ihre tasche", "die tasche ", "tasche auf", "taschen auf", "taschen leer", "taschen aus", "in ihrer tasche", "in ihren taschen", "handtasch", "hosentasch", "jackentasch", "durchsuch", "durch such", "abtasten", "tasten sie ab", "abgetastet", "taste sie", "tastet sie", "tasten sie", "nach waffen", "rucksack", "обыск", "карман", "сумк", "рюкзак"], ["hände aus den taschen", "hände aus der tasche", "hände aus ihren taschen", "hände aus den hosentaschen", "nehmen sie die hände"]],
      ["person-handy", "Handy mitnehmen, entsperren", "Телефон забирают", ["handy ", "handy durchsuch", "handy durch such", "durch suchen ihr handy", "durchsuchen ihr handy", "entsperr", "pin ", "telefon ", "mobiltelefon", "smartphone", "телефон", "разблок"], ["rufen sie ruhig", "können sie jemanden anrufen", "können jemanden anrufen", "dürfen sie telefonieren", "können sie telefonieren", "dürfen telefonieren"]],
      ["aufnahme-filmen-stoppen", "Filmen aufhören", "Прекратить съёмку", ["filmen", "sie filmen", "auf zu filmen", "aufnehm", "aufnahme", "ihre kamera", "kamera aus", "video aus", "handy runter", "handy weg", "smartphone weg", "fotografier", "keine fotos", "снимать", "съёмк", "запись ", "прекратите сним", "опустите телефон"], ["dürfen gern filmen", "dürfen gerne filmen", "dürfen ruhig filmen", "dürfen sie gern", "dürfen sie gerne", "dürfen sie ruhig", "können gern filmen", "können gerne filmen", "können ruhig filmen", "filmen sie ruhig", "filmen sie gern", "filmen dürfen sie", "filmen ist erlaubt", "ihr gutes recht", "stört uns nicht", "nichts zu verbergen"]],
      ["person-weggehen", "Hier stehen bleiben", "Стойте здесь", ["stehen bleiben", "bleiben sie hier", "bleiben hier", "hier stehen", "nicht weggehen", "sie bleiben", "sie bleibet", "bis wir fertig", "bis mir fertig", "стойте", "не уходите", "оставайтесь"]],
      ["person-wache", "Mitkommen auf die Wache", "В участок", ["wache", "revier", "mitkommen", "kommen mit", "kommen sie mit", "dienststelle", "präsidium", "участок", "отдел", "пройдёмте", "поедете с нами"]],
      ["person-angehoerige", "Ehepartner, Verwandte", "Жена, муж, родные", ["seine frau", "seine frau ", "ihre frau", "ihre frau ", "ihr mann", "ihr mann ", "frau des fahrer", "mann der fahrerin", "meine frau", "mein mann", "ehepartner", "ehefrau", "ehemann", "verheiratet", "verlobt", "verwandt", "bruder", "schwester", "жена", "муж ", "мужа", "дружин", "чоловік", "родствен", "родич"]],
      ["person-auslaender-pass", "Pass, Aufenthaltstitel", "Паспорт, ВНЖ", ["pass ", "reisepass", "aufenthalt", "duldung", "visum", "внж", "вид на жительство", "загранпаспорт"], ["pass auf", "passen sie auf", "grund ihres aufenthalt", "zweck ihres aufenthalt"]]
    ],
    fuss: [
      ["person-personalien", "Name, Adresse", "Имя, адрес", ["halten sie sich", "grund ihres aufenthalt", "personalien", "ausweis", "personalausweis", "name", "geburtsdatum", "adresse", "wie heißen", "wo wohnen", "имя", "фамили", "адрес", "дата рождения", "документ", "perso ", "mit lichtbild", "lichtbildausweis", "dokument dabei", "dokumente dabei", "sind sie gemeldet", "sie gemeldet sind", "wohnhaft", "staatsang", "nationalität"]],
      ["person-auslaender-pass", "Pass, Aufenthaltstitel", "Паспорт, ВНЖ", ["pass ", "reisepass", "aufenthalt", "duldung", "visum", "внж", "вид на жительство", "паспорт"], ["pass auf", "passen sie auf", "grund ihres aufenthalt", "zweck ihres aufenthalt"]],
      ["person-grund", "Grund? „Normale Kontrolle“", "Причина?", ["grund ", "normale kontrolle", "allgemeine kontrolle", "verdachtsunabhängig", "причин", "обычная проверка", "allgemeine personenkontrolle", "normale personenkontrolle", "jeden kontrollieren", "jeden hier kontrollieren"], ["grund ihres aufenthalt", "grund halten sie sich", "welchem grund halten"]],
      ["person-taschen-durchsuchen", "Taschen durchsuchen", "Обыск, карманы", ["taschen", "tasche ", "durchsuch", "abtasten", "tasten sie ab", "abgetastet", "rucksack", "обыск", "карман", "сумк", "рюкзак", "alles aus ihren", "ihre hosentasche", "die hosentasche", "in ihren hosentasche", "in ihrer hosentasche", "tasch uff", "taste sie", "nach waffen"], ["hände aus den taschen", "hände aus der tasche", "hände aus ihren taschen", "hände aus den hosentaschen", "nehmen sie die hände"]],
      ["person-handy", "Handy mitnehmen, entsperren", "Телефон забирают", ["handy durchsuch", "durchsuchen ihr handy", "entsperr", "pin ", "smartphone", "телефон", "разблок", "handy ", "handys ", "telefon ", "mobiltelefon "], ["rufen sie ruhig", "können sie jemanden anrufen", "können jemanden anrufen", "dürfen sie telefonieren", "können sie telefonieren", "dürfen telefonieren"]],
      ["aufnahme-filmen-stoppen", "Filmen aufhören", "Прекратить съёмку", ["filmen", "sie filmen", "aufnehm", "aufnahme", "ihre kamera", "kamera aus", "video aus", "handy runter", "handy weg", "smartphone weg", "fotografier", "keine fotos", "снимать", "съёмк", "запись ", "прекратите сним", "опустите телефон", "nicht gefilmt", "kamera runter", "kamera weg"], ["dürfen gern filmen", "dürfen gerne filmen", "dürfen ruhig filmen", "dürfen sie gern", "dürfen sie gerne", "dürfen sie ruhig", "können gern filmen", "können gerne filmen", "können ruhig filmen", "filmen sie ruhig", "filmen sie gern", "filmen dürfen sie", "filmen ist erlaubt", "ihr gutes recht", "stört uns nicht", "nichts zu verbergen"]],
      ["person-weggehen", "Hier stehen bleiben", "Стойте здесь", ["stehen bleiben", "bleiben sie hier", "bleiben hier", "hier stehen", "nicht weggehen", "sie bleiben", "стойте", "не уходите", "оставайтесь", "bleiben sie stehen", "bleiben sie da ", "dageblieben", "hiergeblieben", "bleibet se "]],
      ["person-platzverweis", "Platzverweis, weggehen", "Уйти с места", ["platzverweis", "verlassen", "gehen sie weg", "gehen sie weiter", "hauen sie ab", "verschwinden sie", "weitergehen", "уходите", "покиньте", "platz verweis", "aufenthaltsverbot", "weiterlauf", "laufen sie weiter"]],
      ["person-wache", "Mitkommen auf die Wache", "В участок", ["wache", "revier", "mitkommen", "kommen mit", "kommen sie mit", "dienststelle", "präsidium", "участок", "отдел", "пройдёмте", "поедете с нами"]],
      ["person-fotos-fingerabdruecke", "Fotos, Fingerabdrücke", "Фото, отпечатки", ["fotos von ihnen", "foto von ihnen", "fingerabdr", "erkennungsdienst", "сфотографир", "отпечат", "finger abdr"]]
    ],
    filme: [
      ["aufnahme-filmen-stoppen", "Filmen aufhören", "Прекратить съёмку", ["filmen", "sie filmen", "aufnehm", "aufnahme", "ihre kamera", "kamera aus", "handy runter", "handy weg", "smartphone weg", "fotografier", "keine fotos", "снимать", "съёмк", "запись ", "прекратите сним", "опустите телефон", "nicht gefilmt", "stecken sie das handy", "stecken sie ihr handy", "packen sie das handy", "handy bitte weg", "handy sofort weg", "auf zu film", "uff zu film"], ["dürfen gern filmen", "dürfen gerne filmen", "dürfen ruhig filmen", "dürfen sie gern", "dürfen sie gerne", "dürfen sie ruhig", "können gern filmen", "können gerne filmen", "können ruhig filmen", "filmen sie ruhig", "filmen sie gern", "filmen dürfen sie", "filmen ist erlaubt", "ihr gutes recht", "stört uns nicht", "nichts zu verbergen"]],
      ["aufnahme-201-strafbar", "„Ton ist strafbar“", "«Звук — преступление»", ["tonaufnahm", "201", "strafbar", "звук", "уголовн", "mit ton", "ohne ton", "auch ton", "ton ab", "ton aus", "ton auf", "ton an ", "ton mit", "ton ist verb", "ton ist nicht erlaubt", "bild und ton", "ton und bild", "vertraulichkeit", "gesprochene wort", "gesprochenen wort"]],
      ["aufnahme-bildrecht-kug", "„Recht am eigenen Bild“", "«Право на изображение»", ["eigenen bild", "bildrecht", "persönlichkeitsrecht", "изображени", "собственное изображени", "gesichter", "mein gesicht", "unser gesicht", "gesicht von"]],
      ["aufnahme-ausweis-wegen-filmen", "Ausweis wegen Filmen", "Документы за съёмку", ["ausweis", "ihren ausweis", "zeigen sie mir", "personalausweis", "personalien", "ausweisen", "документ", "паспорт", "посвідч", "weisen sie sich", "geburtsdatum", "anschrift"], ["ihr bekannter muss sich", "ihre bekannte muss sich", "ihr freund muss sich", "ihre freundin muss sich"]],
      ["aufnahme-platzverweis-filmer", "Platzverweis, weggehen", "Уйти с места", ["platzverweis", "gehen sie weg", "gehen sie weiter", "behindern", "уходите", "покиньте", "мешаете", "bitte weitergehen", "weitergehen bitte", "sofort weitergehen", "platz verweis", "meter abstand", "halten sie abstand", "abstand halten", "mehr abstand", "auf abstand", "treten sie zurück", "treten sie bitte zurück", "zurücktreten", "gehen sie zurück", "bleiben sie zurück", "entfernen sie sich", "sie stören die", "sie stören den", "sie stören eine", "gehn se weiter", "gehn sie weiter", "nichts zu sehen", "nix zu sehen", "verlassen sie", "bereich verlassen", "ort verlassen", "platz verlassen", "sofort verlassen"]],
      ["aufnahme-loeschen", "Video löschen", "Удалить видео", ["lösch", "löschen sie", "удал", "стер", "entfernen sie die aufnahme", "entfernen sie das video", "aufnahme entfern", "video entfern", "entfernt werden"]],
      ["aufnahme-zeuge-video-herausgeben", "„Sie sind Zeuge, Handy her“", "«Вы свидетель, дайте телефон»", ["zeuge", "video her", "свидетел", "свідок"]],
      ["aufnahme-handy-herausgeben", "Handy beschlagnahmt", "Телефон изымают", ["handy", "beschlagnahm", "geben sie mir", "телефон", "изым"]],
      ["aufnahme-pin-entsperren", "PIN, entsperren", "PIN, разблокировать", ["pin ", "entsperr", "code ", "разблок", "пароль", "пин ", "den code", "ihren code", "code für", "pincode", "passcode", "passwort", "den pin", "die pin", "ihren pin", "ihrem pin"]],
      ["person-zeuge-aussage", "Aussagen als Zeuge", "Показания свидетеля", ["aussagen", "aussage", "gesehen", "показани", "дать показани", "видели", "что вы видели", "gsehe", "zeugenaussage", "zeugenvernehm"]]
    ]
  },
  // Nur für „Stichwort sagen“ und Mithören: Einträge ohne eigenen Knopf (volle Antwort aus quick.js)
  extra: {
    fahrer: [["person-telefonnummer", ["handynummer", "handy nummer", "telefonnummer", "номер телефона", "telefon nummer", "mobilnummer", "ihre nummer", "e mail", "email", "bei wem arbeiten", "ihr arbeitgeber", "ihren arbeitgeber"]], ["aufnahme-eigene-kamera", ["selbst eine kamera", "selbst eine bodycam", "eigene kamera", "wir filmen selbst", "wir filmen doch", "wir nehmen selbst", "müssen nicht filmen", "brauchen nicht filmen", "brauchen nicht zu filmen", "haben eine bodycam", "haben bodycam", "своя камера", "у нас камера", "у нас есть камера", "мы сами снимаем", "нательн"]], ["aufnahme-bodycam-sichern", ["bodycam ein", "bodycam jetzt ein", "kamera ein", "schalte die kamera", "meiner bodycam", "ich zeichne", "zeichne ich", "wir zeichnen", "включаю камер", "включаю нательн", "bodycam an", "bodycam läuft", "bodycam nimmt"]], ["aufnahme-bildrecht-kug", ["gesicht", "gesichter", "eigenen bild", "bildrecht", "persönlichkeitsrecht", "лиц", "изображени"]], ["aufnahme-201-strafbar", ["ton ", "tonaufnahm", "201", "vertraulichkeit", "gesprochene wort", "звук"]], ["fahrer-warnausruestung", ["warndreieck", "verbandkasten", "verbandskasten", "warnweste", "аптечк", "аварийный знак", "жилет"]],
      ["fahrer-handy-weg-haende", ["hände", "lenkrad", "hände ans lenkrad", "handy weg", "smartphone weg", "legen sie das handy", "finger vom handy", "finger weg vom handy", "handy mal weg", "handy bitte weg", "handy jetzt weg", "handy sofort weg", "руки", "руль"]], ["aufnahme-loeschen", ["lösch", "удал", "стер", "видал"]], ["druck-freiwillig-mitkommen", ["freiwillig mit", "freiwillig auf die wache", "freiwillig zur wache", "freiwillig zum revier", "freiwillig aufs revier", "freiwillig auf das revier", "freiwillig begleiten", "freiwillig zur dienststelle", "freiwillig auf die dienststelle", "добровольно"]], ["aufnahme-nehmen-sie-auf", ["sie das auf", "das etwa auf", "etwa auf", "nehmen sie auf", "nehmen sie uns auf", "filmen sie etwa", "filmen sie uns", "zeichnen sie auf", "gerade eine aufnahme", "läuft eine aufnahme", "läuft bei ihnen", "вы снимаете", "вы записываете"]], ["aufnahme-livestream", ["livestream", "live stream", "streamen", "трансляц", "стрим"]]],
    beifahrer: [["person-telefonnummer", ["handynummer", "handy nummer", "telefonnummer", "номер телефона", "telefon nummer", "mobilnummer", "ihre nummer", "e mail", "email", "bei wem arbeiten", "ihr arbeitgeber", "ihren arbeitgeber"]], ["person-durchsuchung-geschlecht", ["weibliche kollegin", "eine kollegin", "keine kollegin", "eine beamtin", "keine beamtin", "männlicher kollege", "gleichen geschlecht", "von einer frau", "von einem mann"]], ["aufnahme-eigene-kamera", ["selbst eine kamera", "selbst eine bodycam", "eigene kamera", "wir filmen selbst", "wir filmen doch", "wir nehmen selbst", "müssen nicht filmen", "brauchen nicht filmen", "brauchen nicht zu filmen", "haben eine bodycam", "haben bodycam", "своя камера", "у нас камера", "у нас есть камера", "мы сами снимаем", "нательн"]], ["aufnahme-bodycam-sichern", ["bodycam ein", "bodycam läuft", "bodycam ist an", "bodycam ist ein", "bodycam an ", "bodycam jetzt ein", "kamera ein", "schalte die kamera", "включаю камер", "включаю нательн", "bodycam nimmt"]], ["aufnahme-bildrecht-kug", ["gesicht", "gesichter", "eigenen bild", "bildrecht", "persönlichkeitsrecht", "лиц", "изображени"]], ["aufnahme-201-strafbar", ["den ton ", "ohne ton", "mit ton ", "ton aus", "ton ab", "tonaufnahm", "201", "vertraulichkeit", "gesprochene wort", "звук"]], ["druck-unterschreiben", ["unterschreib", "unterschrift", "подпис", "подпиш"]], ["aufnahme-loeschen", ["lösch", "gelöscht", "удал", "стер", "видал"]], ["druck-freiwillig-mitkommen", ["freiwillig mit", "freiwillig zum", "freiwillig zur", "freiwillig aufs", "freiwillig auf die wache", "freiwillig zur wache", "добровольно"]], ["aufnahme-nehmen-sie-auf", ["sie das auf", "etwa eine aufnahme", "läuft eine aufnahme", "läuft da eine aufnahme", "das etwa auf", "etwa auf", "nehmen sie auf", "nehmen sie uns auf", "filmen sie etwa", "filmen sie uns", "zeichnen sie auf", "вы снимаете", "вы записываете"]], ["aufnahme-livestream", ["livestream", "live stream", "streamen", "трансляц", "стрим"]]],
    fuss: [["person-telefonnummer", ["handynummer", "handy nummer", "telefonnummer", "номер телефона", "telefon nummer", "mobilnummer", "ihre nummer", "e mail", "email", "bei wem arbeiten", "ihr arbeitgeber", "ihren arbeitgeber"]], ["person-durchsuchung-geschlecht", ["weibliche kollegin", "eine kollegin", "keine kollegin", "eine beamtin", "keine beamtin", "männlicher kollege", "gleichen geschlecht", "von einer frau", "von einem mann"]], ["person-waffenverbotszone", ["waffenverbotszone", "waffenverbot", "messerverbot", "verbotszone"]], ["person-zeuge-aussage", ["als zeuge", "zeugenaussage", "zeugenvernehm", "zeuge ", "zeugin "]], ["aufnahme-eigene-kamera", ["selbst eine kamera", "selbst eine bodycam", "eigene kamera", "wir filmen selbst", "wir filmen doch", "wir nehmen selbst", "müssen nicht filmen", "brauchen nicht filmen", "brauchen nicht zu filmen", "haben eine bodycam", "haben bodycam", "своя камера", "у нас камера", "у нас есть камера", "мы сами снимаем", "нательн"]], ["aufnahme-bodycam-sichern", ["bodycam ein", "bodycam jetzt ein", "kamera ein", "schalte die kamera", "включаю камер", "включаю нательн", "bodycam läuft", "bodycam ist an", "bodycam ist eingeschaltet", "von der bodycam", "aufnahme der bodycam", "automatisch gelöscht", "bodycam an", "bodycam nimmt"]], ["aufnahme-bildrecht-kug", ["gesicht", "gesichter", "eigenen bild", "bildrecht", "persönlichkeitsrecht", "лиц", "изображени"]], ["aufnahme-201-strafbar", ["ton ", "tonaufnahm", "201", "vertraulichkeit", "gesprochene wort", "звук"]], ["aufnahme-loeschen", ["lösch", "удал", "стер", "видал"]], ["druck-freiwillig-mitkommen", ["freiwillig mit", "freiwillig auf die wache", "freiwillig zur wache", "добровольно", "freiwillig mitkommen"]], ["aufnahme-nehmen-sie-auf", ["sie das auf", "das etwa auf", "etwa auf", "nehmen sie auf", "nehmen sie uns auf", "filmen sie etwa", "filmen sie uns", "zeichnen sie auf", "вы снимаете", "вы записываете"]], ["aufnahme-livestream", ["livestream", "live stream", "streamen", "трансляц", "стрим", "sie live", "gerade live"]]],
    filme: [["aufnahme-eigene-kamera", ["selbst eine kamera", "selbst eine bodycam", "eigene kamera", "wir filmen selbst", "wir filmen doch", "wir nehmen selbst", "müssen nicht filmen", "brauchen nicht filmen", "brauchen nicht zu filmen", "haben eine bodycam", "haben bodycam", "своя камера", "у нас камера", "у нас есть камера", "мы сами снимаем", "нательн", "müssen das nicht filmen", "selbst eine body cam", "haben eine body cam"]], ["aufnahme-bodycam-sichern", ["bodycam ein", "bodycam jetzt ein", "kamera ein", "schalte die kamera", "включаю камер", "включаю нательн", "bodycam an", "body cam an", "body cam ein", "bodycam läuft", "bodycam nimmt"]], ["aufnahme-loeschen", ["lösch", "удал", "стер", "видал"]], ["druck-freiwillig-mitkommen", ["freiwillig mit", "freiwillig auf die wache", "freiwillig zur wache", "добровольно"]], ["aufnahme-nehmen-sie-auf", ["sie das auf", "das etwa auf", "etwa auf", "nehmen sie auf", "nehmen sie uns auf", "filmen sie etwa", "filmen sie uns", "zeichnen sie auf", "вы снимаете", "вы записываете", "das hier gerade auf", "das gerade auf", "uns gerade auf", "eine aufnahme", "aufnahme läuft", "läuft die aufnahme"]], ["aufnahme-livestream", ["livestream", "live stream", "streamen", "трансляц", "стрим", "live "]], ["person-weggehen", ["stehen bleiben", "bleiben sie hier", "hier stehen", "стойте", "не уходите"]]]
  },
  kurz: {
    "aufnahme-201-strafbar": { de: "Dann schalte ich den Ton ab und filme nur Bild.", ru: "Тогда выключаю звук и снимаю только изображение.", law: "§ 201 Abs. 1 Nr. 1 StGB" },
    "aufnahme-bildrecht-kug": { de: "§ 22 KUG verbietet nur das Verbreiten, nicht das Filmen. Ich veröffentliche nichts.", ru: "§ 22 KUG запрещает только распространять, а не снимать. Ничего не публикую.", law: "§§ 22, 33 KUG" },
    "aufnahme-ausweis-wegen-filmen": { de: "Nennen Sie mir bitte den Grund. Meine Personalien nenne ich trotzdem.", ru: "Назовите, пожалуйста, основание. Свои данные я всё равно назову.", law: "§ 27 Abs. 1 Nr. 1 PolG BW · § 111 OWiG" },
    "aufnahme-platzverweis-filmer": { de: "Ich gehe sofort. Ich filme außerhalb des Bereichs weiter.", ru: "Сразу ухожу. Продолжу снимать за пределами зоны.", law: "§ 30 Abs. 1 PolG BW",
      dann: "Immer sofort befolgen – prüfen lassen kannst du ihn später.", dann_ru: "Выполнять всегда сразу — обжаловать можно потом." },
    "aufnahme-zeuge-video-herausgeben": { de: "Eine Kopie des Videos gebe ich gern. Das Handy nicht freiwillig – einer Beschlagnahme widerspreche ich ohne Widerstand.", ru: "Копию видео дам охотно. Телефон добровольно не отдаю — против изъятия возражаю без сопротивления.", law: "§§ 94, 95, 98 Abs. 2 StPO" },
    "aufnahme-handy-herausgeben": { de: "Freiwillig gebe ich es nicht heraus. Ich widerspreche der Beschlagnahme, Widerstand leiste ich nicht.", ru: "Добровольно не отдаю. Возражаю против изъятия, сопротивления не оказываю.", law: "§§ 94, 98 Abs. 2 StPO",
      dann: "Nimmt er es: loslassen, nicht festhalten, Bescheinigung verlangen.", dann_ru: "Если забирает: отпустить, не удерживать, потребовать справку." },
    "aufnahme-pin-entsperren": { de: "Den PIN nenne ich nicht und entsperre nicht. Widerstand leiste ich nicht.", ru: "PIN не называю и не разблокирую. Сопротивления не оказываю.", law: "§ 136 Abs. 1 S. 2 StPO",
      dann: "Ausnahme: Ausländer ganz ohne gültige Ausweispapiere (§ 48 Abs. 3a AufenthG).", dann_ru: "Исключение: иностранец вообще без действующих документов, удостоверяющих личность (§ 48 Abs. 3a AufenthG)." },
    "person-zeuge-aussage": { de: "Meine Personalien gebe ich an. Bei der Polizei sage ich nur auf Ladung im Auftrag der Staatsanwaltschaft aus.", ru: "Свои данные назову. В полиции даю показания только по вызову по поручению прокуратуры.", law: "§ 163 Abs. 3 S. 1 StPO" },
    "aufnahme-loeschen": { de: "Ich lösche nichts. Einer Beschlagnahme widerspreche ich, Widerstand leiste ich nicht.", ru: "Ничего не удаляю. Против изъятия возражаю, сопротивления не оказываю.", law: "§§ 94, 98 Abs. 1 StPO",
      dann: "Beschlagnahmt er das Handy: loslassen, nicht festhalten.", dann_ru: "Если изымает телефон: отпустить, не удерживать." },
    "druck-freiwillig-mitkommen": { de: "Ist das eine Anordnung? Freiwillig komme ich nicht mit. Einer Anordnung folge ich ohne Widerstand.", ru: "Это распоряжение? Добровольно не пойду. Распоряжению подчинюсь без сопротивления.", law: "Art. 104 Abs. 1 GG" },
    "aufnahme-nehmen-sie-auf": { de: "Ja, offen und nur Bild ohne Ton. Ich veröffentliche nichts.", ru: "Да, открыто и только изображение без звука. Ничего не публикую.", law: "§ 201 Abs. 1 Nr. 1 StGB · § 22 KUG",
      dann: "Nie leugnen. Läuft Ton mit: offen sagen und den Ton ausschalten, wenn er widerspricht.", dann_ru: "Никогда не отрицай. Если пишется звук: скажи прямо и выключи звук, если он возражает." },
    "aufnahme-eigene-kamera": { de: "Ihre Bodycam löscht ohne Gefahr für Leib oder Leben nach 60 Sekunden. Ich filme nur Bild ohne Ton.", ru: "Ваша камера без опасности для жизни или здоровья удаляет запись через 60 секунд. Снимаю только изображение без звука.", law: "§ 44 Abs. 8, 11 PolG BW",
      dann: "Nicht diskutieren. Ordnet er das Aufhören an: befolgen und widersprechen.", dann_ru: "Не спорить. Если прикажет прекратить: подчиниться и возразить." },
    "aufnahme-bodycam-sichern": { de: "In Ordnung. Bitte bewahren Sie die Aufnahme als Beweis auf und löschen Sie sie nicht.", ru: "Хорошо. Прошу сохранить запись как доказательство и не удалять.", law: "§ 44 Abs. 10 S. 2 PolG BW" },
    "aufnahme-livestream": { de: "Ich beende den Livestream und speichere nur privat.", ru: "Прекращаю трансляцию и сохраняю только для себя.", law: "§§ 22, 33 KUG" },
    "fahrer-handy-weg-haende": { de: "Mache ich. Das Handy kommt in die Halterung, meine Hände bleiben sichtbar.", ru: "Выполняю. Телефон в держатель, руки на виду.", law: "§ 36 Abs. 5 S. 4 StVO" },
    "person-angehoerige": { de: "Ich bin mit dem Fahrer verheiratet. Ich verweigere die Aussage.", ru: "Я в браке с водителем. Отказываюсь давать показания.", law: "§ 52 Abs. 1 StPO",
      dann: "Das gilt auch für Verlobte, Eltern, Kinder und Geschwister.", dann_ru: "То же касается жениха или невесты, родителей, детей, братьев и сестёр." },
    "fahrer-papiere": { de: "Bitte sehr. Zur Sache sage ich nichts.", ru: "Пожалуйста. По существу ничего не скажу.", law: "§ 4 Abs. 2 S. 2 FeV · § 13 Abs. 6 S. 1 FZV" },
    "fahrer-fragen": { de: "Meine Personalien gebe ich an. Weitere Fragen beantworte ich nicht.", ru: "Личные данные назову. На другие вопросы не отвечаю.", law: "§ 43 Abs. 1 S. 2 PolG BW · § 136 Abs. 1 S. 2 StPO" },
    "fahrer-pusten": { de: "Ist das eine Anordnung? Einem Atemalkoholtest stimme ich nicht zu. § 81a StPO verlangt nur Dulden.", ru: "Это распоряжение? На алкотест не соглашаюсь. § 81a StPO требует только терпеть.", law: "§ 81a Abs. 1 StPO" },
    "fahrer-drogenvortest": { de: "Urin-, Speichel- und Koordinationstests mache ich nicht mit. Eine Anordnung nach § 81a StPO dulde ich.", ru: "В тестах мочи, слюны и на координацию не участвую. Распоряжение по § 81a StPO стерплю.", law: "§ 81a Abs. 1 StPO" },
    "fahrer-blut": { de: "Ich stimme nicht zu, leiste aber keinen Widerstand. Wer hat das angeordnet, auf welche Tatsachen?", ru: "Не соглашаюсь, но сопротивляться не буду. Кто это назначил и на каких фактах?", law: "§ 81a Abs. 2 StPO",
      dann: "Wird die Blutentnahme angeordnet: dulden, nicht wehren.", dann_ru: "Если взятие крови назначено: терпеть, не сопротивляться." },
    "fahrer-aussteigen": { de: "Ich steige aus. Zur Sache sage ich nichts, freiwilligen Tests stimme ich nicht zu.", ru: "Выхожу. По существу ничего не скажу, на добровольные тесты не соглашаюсь.", law: "§ 36 Abs. 5 StVO" },
    "fahrer-kofferraum": { de: "Einer Durchsuchung stimme ich nicht zu. Auf welcher Grundlage? Ich leiste keinen Widerstand.", ru: "На обыск не соглашаюсь. На каком основании? Сопротивляться не буду.", law: "§ 102 StPO · § 35 PolG BW",
      dann: "Durchsucht er trotzdem: dulden, nicht helfen.", dann_ru: "Если всё равно обыскивает: терпеть, не помогать." },
    "fahrer-handy": { de: "Zum Vorwurf sage ich nichts. Mein Handy entsperre ich nicht, den Code nenne ich nicht.", ru: "По обвинению ничего не скажу. Телефон не разблокирую, код не назову.", law: "§ 136 Abs. 1 S. 2 StPO",
      dann: "Beschlagnahmt er es: keinen Widerstand leisten. Den PIN musst du nicht nennen – Ausnahme: Ausländer ganz ohne gültige Ausweispapiere (§ 48 Abs. 3a AufenthG).", dann_ru: "Если изымает: не сопротивляться. PIN называть не нужно — исключение: иностранец вообще без действующих документов, удостоверяющих личность (§ 48 Abs. 3a AufenthG)." },
    "aufnahme-filmen-stoppen": { de: "Ich behindere Sie nicht und veröffentliche nichts. Ordnen Sie es an, folge ich unter Widerspruch.", ru: "Я вам не мешаю и ничего не публикую. Если прикажете, подчинюсь, но с возражением.", law: "§§ 1, 3 PolG BW",
      dann: "Ordnet er es an: aufhören und später gerichtlich prüfen lassen.", dann_ru: "Если приказал: прекратить и потом обжаловать в суде." },
    "fahrer-unterschrift": { de: "Ich unterschreibe nichts und sage nichts zur Sache. Eine Kopie nehme ich gern.", ru: "Ничего не подписываю и по существу не говорю. От копии не откажусь.", law: "§ 136 Abs. 1 S. 2 StPO" },
    "person-beifahrer-ausweis": { de: "Ich bin nur Beifahrer. Auf welcher Rechtsgrundlage?", ru: "Я только пассажир. На каком основании?", law: "§ 27 PolG BW · § 163b StPO",
      dann: "Besteht er darauf: Personalien unter Widerspruch angeben, mitgeführten Ausweis zeigen.", dann_ru: "Если настаивает: назвать данные с возражением, показать документ, если он с собой." },
    "druck-zeuge-beifahrer": { de: "Hier sind meine Personalien. Bei der Polizei sage ich nur auf Ladung im Auftrag der Staatsanwaltschaft aus.", ru: "Вот мои данные. В полиции даю показания только по вызову по поручению прокуратуры.", law: "§ 163 Abs. 3 S. 1 StPO" },
    "person-grund": { de: "Werde ich einer Straftat verdächtigt? Dann nennen Sie mir bitte die Tat.", ru: "Меня подозревают в преступлении? Тогда назовите, в каком.", law: "§ 163b Abs. 1 · § 163a Abs. 4 S. 1 StPO",
      dann: "Nach § 27 PolG BW muss er den Grund nicht sofort nennen. Personalien trotzdem angeben und gleich eine schriftliche Bestätigung verlangen.", dann_ru: "По § 27 PolG BW причину сразу называть не обязаны. Данные всё равно назови и сразу потребуй письменное подтверждение." },
    "person-taschen-durchsuchen": { de: "Ich stimme der Durchsuchung nicht zu und leiste keinen Widerstand. Auf welcher Grundlage?", ru: "Не согласен на обыск и не сопротивляюсь. На каком основании?", law: "§ 34 PolG BW · § 102 StPO",
      dann: "Durchsucht er trotzdem: dulden, nicht wehren.", dann_ru: "Если всё равно обыскивает: терпеть, не сопротивляться." },
    "person-handy": { de: "Ich gebe das Handy nicht freiwillig heraus und widerspreche der Beschlagnahme. Meinen PIN nenne ich nicht.", ru: "Телефон добровольно не отдаю и возражаю против изъятия. PIN не называю.", law: "§ 98 Abs. 2 · § 136 Abs. 1 S. 2 StPO",
      dann: "Nimmt er es trotzdem: keinen Widerstand leisten, Bescheinigung verlangen. PIN-Ausnahme: Ausländer ganz ohne gültige Ausweispapiere (§ 48 Abs. 3a AufenthG).", dann_ru: "Если всё равно забирает: не сопротивляться, потребовать справку. Исключение по PIN: иностранец вообще без действующих документов, удостоверяющих личность (§ 48 Abs. 3a AufenthG)." },
    "person-weggehen": { de: "Werde ich festgehalten, und auf welcher Grundlage? Wenn nicht, möchte ich jetzt gehen.", ru: "Меня задерживают, и на каком основании? Если нет, хочу сейчас уйти.", law: "§ 27 Abs. 2 S. 3 PolG BW · § 163b StPO",
      dann: "Hält er dich fest: bleib, wehr dich nicht, lass es später prüfen.", dann_ru: "Если задерживает: оставайся, не сопротивляйся, обжалуй потом." },
    "person-wache": { de: "Ich komme mit, leiste keinen Widerstand, widerspreche aber. Warum ist meine Identität hier nicht feststellbar?", ru: "Поеду, не сопротивляюсь, но возражаю. Почему мою личность нельзя установить здесь?", law: "§ 163b Abs. 1 S. 2 · § 163c StPO",
      dann: "Verlange, einen Angehörigen zu benachrichtigen.", dann_ru: "Потребуй сообщить родственнику." },
    "druck-unterschreiben": { de: "Ich unterschreibe nichts. Eine Pflicht zur Unterschrift gibt es nicht.", ru: "Ничего не подписываю. Обязанности подписывать нет.", law: "§ 168a Abs. 3 StPO" },
    "person-auslaender-pass": { de: "Hier sind mein Pass und mein Aufenthaltstitel. Zur Sache sage ich nichts.", ru: "Вот мой паспорт и вид на жительство. По делу ничего не скажу.", law: "§§ 47a, 48 Abs. 1 AufenthG" },
    "person-personalien": { de: "Hier sind meine Personalien. Zu allem Weiteren sage ich nichts.", ru: "Вот мои данные. Больше ничего не скажу.", law: "§ 111 OWiG" },
    "person-platzverweis": { de: "Ich gehe. Nennen Sie mir bitte die Gefahr, den Bereich und die Dauer.", ru: "Ухожу. Назовите, пожалуйста, опасность, территорию и срок.", law: "§ 30 Abs. 1 PolG BW" },
    "person-fotos-fingerabdruecke": { de: "Bin ich Beschuldigter oder Zeuge? Ich widerspreche, leiste aber keinen Widerstand.", ru: "Я обвиняемый или свидетель? Возражаю, но не сопротивляюсь.", law: "§ 81b Abs. 1 · § 163b Abs. 2 StPO",
      dann: "Als Beschuldigter oder wenn deine Identität sonst nicht klärbar ist, musst du es dulden.", dann_ru: "Обвиняемый, или если личность иначе не установить, обязан это терпеть." }
  }
};
