/* „Sagen"-Modus (Fahrer, Beifahrer, Zu Fuß, Rad; nicht „Ich filme“): statt 10 Knöpfen 7 Phasen einer Kontrolle, je Phase ein kurzer deutscher Satz
   zum Vorspielen (vorab erzeugte Audiodatei, Männer- oder Frauenstimme) und Anzeigen.
   Quelle: Probe_Taschenanwalt/daten.json + saetze.json (Prototyp „Anwalt in der Tasche"), 1:1 übernommen.
   ziel/tipp/nicht gab es dort nur auf Russisch – die deutsche Fassung ist eine kurze, sinngemäße Übersetzung,
   keine neue Rechtsaussage. detail = erste Antwort-ID aus den „details" des Prototyps (siehe quick.js/kontrolle.js).
   Beifahrer/Zu Fuß/Rad (28.09.2026): Sätze = Kurzfassungen („kurz“) der geprüften Antworten aus kontrolle.js/quick.js;
   tipp/nicht nur Verhaltenshinweise, die sich aus diesen Antworten ergeben.
   Noch nicht anwaltlich geprüft. */
window.RB = window.RB || {};
window.RB.phasen = {
  saetze: {
    "s-start": { de: "Guten Tag. Ich spreche wenig Deutsch, mein Handy spricht für mich.", ru: "Добрый день. Я плохо говорю по-немецки, за меня говорит телефон." },
    "s-video": { de: "Zur Info: Mein Handy filmt offen, nur Bild, ohne Ton.", ru: "Для информации: телефон снимает открыто, только картинка, без звука." },
    "s-handy": { de: "Ich greife jetzt langsam zu meinem Handy.", ru: "Я сейчас медленно беру телефон." },
    "s-papiere": { de: "Bitte sehr, hier sind Führerschein und Fahrzeugschein.", ru: "Пожалуйста, вот права и техпаспорт." },
    "s-warn": { de: "Die Sachen liegen griffbereit. Ich reiche sie Ihnen durchs Fenster.", ru: "Вещи под рукой. Передам их вам через окно." },
    "s-aussteigen": { de: "Ich steige aus. Zur Sache sage ich nichts.", ru: "Я выхожу. По существу ничего не скажу." },
    "s-zursache": { de: "Meine Personalien gebe ich an. Zur Sache sage ich nichts.", ru: "Свои данные назову. По существу ничего не скажу." },
    "s-test": { de: "Einem freiwilligen Test stimme ich nicht zu.", ru: "На добровольный тест не соглашаюсь." },
    "s-anordnung": { de: "Ist das eine Anordnung?", ru: "Это распоряжение?" },
    "s-durchsuchung": { de: "Einer Durchsuchung stimme ich nicht zu. Widerstand leiste ich nicht.", ru: "На обыск не соглашаюсь. Сопротивления не оказываю." },
    "s-grundlage": { de: "Auf welcher Rechtsgrundlage, bitte?", ru: "На каком правовом основании, пожалуйста?" },
    "s-widerspruch": { de: "Ich widerspreche, leiste aber keinen Widerstand. Bitte vermerken Sie das.", ru: "Я возражаю, но не сопротивляюсь. Пожалуйста, занесите это в протокол." },
    "s-ende": { de: "Ist die Kontrolle für mich beendet?", ru: "Проверка для меня закончена?" },
    "s-personalien": { de: "Hier sind meine Personalien. Zu allem Weiteren sage ich nichts.", ru: "Вот мои данные. Больше ничего не скажу." },
    "s-pass": { de: "Hier sind mein Pass und mein Aufenthaltstitel.", ru: "Вот мой паспорт и вид на жительство." },
    "s-grund": { de: "Werde ich einer Straftat verdächtigt? Dann nennen Sie mir bitte die Tat.", ru: "Меня подозревают в преступлении? Тогда назовите, пожалуйста, в каком." },
    "s-festgehalten": { de: "Werde ich festgehalten, und auf welcher Grundlage? Wenn nicht, möchte ich jetzt gehen.", ru: "Меня задерживают, и на каком основании? Если нет — я сейчас пойду." },
    "s-handy-nein": { de: "Ich gebe das Handy nicht freiwillig heraus und widerspreche der Beschlagnahme. Meinen PIN nenne ich nicht.", ru: "Телефон добровольно не отдаю и возражаю против изъятия. PIN не назову." },
    "s-wache": { de: "Ich komme mit, leiste keinen Widerstand, widerspreche aber.", ru: "Я иду с вами, не сопротивляюсь, но возражаю." },
    "s-mitfahrer": { de: "Ich fahre nur mit. Auf welcher Rechtsgrundlage?", ru: "Я только пассажир. На каком правовом основании?" },
    "s-zeuge": { de: "Hier sind meine Personalien. Bei der Polizei sage ich nur auf Ladung im Auftrag der Staatsanwaltschaft aus.", ru: "Вот мои данные. В полиции я даю показания только по вызову от прокуратуры." },
    "s-rahmen": { de: "Die Rahmennummer zeige ich Ihnen gern selbst.", ru: "Номер рамы я вам сам покажу." },
    "s-unterschrift": { de: "Ich unterschreibe nichts und sage nichts zur Sache. Eine Kopie nehme ich gern.", ru: "Я ничего не подписываю и по существу не говорю. Копию возьму." },
    "s-verwarnung": { de: "Mit dem Verwarnungsgeld bin ich nicht einverstanden.", ru: "С предупредительным штрафом я не согласен." }
  },
  fahrer: [
    { k: "start", de: "Anhalten", ru: "Остановка",
      ziel_de: "Ruhe zeigen und die Sprachbarriere entschärfen.", ziel_ru: "Показать спокойствие и снять языковой барьер.",
      main: "s-start", extra: ["s-video", "s-handy"],
      tipp_de: "Licht im Auto an, Fenster runter, Hände ans Lenkrad. Langsam sprechen.", tipp_ru: "Свет в салоне, окно открыть, руки на руле. Говорить медленно.",
      nicht_de: "Nicht ohne Vorwarnung ins Handschuhfach oder in die Tasche greifen.", nicht_ru: "Не тянуться к бардачку или сумке без предупреждения.",
      detail: "aufnahme-nehmen-sie-auf",
      cop_de: "Guten Abend, allgemeine Verkehrskontrolle.", cop_ru: "Добрый вечер, обычная проверка движения." },
    { k: "papiere", de: "Papiere", ru: "Документы",
      ziel_de: "Die Pflicht knapp erfüllen, nichts Zusätzliches sagen.", ziel_ru: "Быстро выполнить обязанность, ничего лишнего.",
      main: "s-papiere", extra: ["s-warn"],
      tipp_de: "Führerschein und Fahrzeugschein ruhig und ohne Worte übergeben. Paragrafen sind hier nicht nötig.", tipp_ru: "Права и техпаспорт отдать молча и спокойно. Параграфы тут не нужны.",
      nicht_de: "Beim Übergeben keine Paragrafen zitieren – klingt auswendig gelernt.", nicht_ru: "Не цитировать параграфы при передаче документов: звучит заучено.",
      detail: "fahrer-papiere",
      cop_de: "Führerschein und Fahrzeugschein, bitte.", cop_ru: "Права и техпаспорт, пожалуйста." },
    { k: "fragen", de: "Fragen", ru: "Вопросы",
      ziel_de: "Die eigenen Daten nennen, zur Sache schweigen.", ziel_ru: "Назвать данные, по существу молчать.",
      main: "s-zursache", extra: ["s-aussteigen"],
      tipp_de: "Erst die Daten, dann diesen Satz. Höflich, ohne Erklärungen.", tipp_ru: "Сначала данные, потом эта фраза. Вежливо, без объяснений.",
      nicht_de: "„Nur ein Glas“, „vor zwei Stunden“ – der häufigste Fehler.", nicht_ru: "«Только один бокал», «часа два назад» — самая частая ошибка.",
      detail: "fahrer-fragen",
      cop_de: "Wo kommen Sie her? Haben Sie heute was getrunken?", cop_ru: "Откуда вы едете? Сегодня что-нибудь пили?" },
    { k: "tests", de: "Tests", ru: "Тесты",
      ziel_de: "Den freiwilligen Test ablehnen, ohne zu streiten.", ziel_ru: "Отказаться от добровольного теста без спора.",
      main: "s-test", extra: ["s-anordnung"],
      tipp_de: "Besteht der Beamte darauf: fragen, ob es eine Anordnung ist.", tipp_ru: "Если настаивают — спросить, распоряжение ли это.",
      nicht_de: "Nicht zustimmen, „damit es schneller vorbei ist“.", nicht_ru: "Не соглашаться «чтобы быстрее закончилось».",
      detail: "fahrer-pusten",
      cop_de: "Pusten Sie mal hier rein.", cop_ru: "Подуйте сюда, пожалуйста." },
    { k: "durchsuchung", de: "Durchsuchung", ru: "Обыск",
      ziel_de: "Nicht zustimmen und keinen Widerstand leisten.", ziel_ru: "Не согласиться и не сопротивляться.",
      main: "s-durchsuchung", extra: ["s-grundlage"],
      tipp_de: "Hände sichtbar halten, nichts anfassen, nicht behindern.", tipp_ru: "Руки видны, ничего не трогать, не мешать.",
      nicht_de: "Tür, Kofferraum oder Tasche nicht festhalten.", nicht_ru: "Не держать дверь, багажник или сумку.",
      detail: "fahrer-kofferraum",
      cop_de: "Machen Sie mal den Kofferraum auf.", cop_ru: "Откройте, пожалуйста, багажник." },
    { k: "massnahme", de: "Zwang", ru: "Принуждение",
      ziel_de: "Für das Protokoll widersprechen, körperlich aber mitmachen.", ziel_ru: "Возразить для протокола, физически подчиниться.",
      main: "s-widerspruch", extra: ["s-grundlage"],
      tipp_de: "Blutprobe, Handy-Beschlagnahme, Wache: mit Worten widersprechen, nicht mit dem Körper.", tipp_ru: "Кровь, изъятие телефона, участок: возражать словами, не телом.",
      nicht_de: "Nicht losreißen oder weglaufen – sonst droht zusätzlich ein Strafverfahren wegen Widerstands.", nicht_ru: "Не вырываться и не убегать — иначе грозит ещё и уголовное дело за сопротивление.",
      detail: "fahrer-blut",
      cop_de: "Dann nehmen wir eben Blut. Kommen Sie mit.", cop_ru: "Тогда возьмём кровь. Пройдёмте с нами." },
    { k: "ende", de: "Ende", ru: "Конец",
      ziel_de: "Höflich nachfragen, ob alles beendet ist.", ziel_ru: "Вежливо уточнить, что всё закончено.",
      main: "s-ende", extra: [],
      tipp_de: "Nach der Kontrolle das Video mit „Jetzt sichern“ speichern.", tipp_ru: "После проверки сохрани видео кнопкой «Jetzt sichern».",
      nicht_de: "Nicht fragen „bin ich verhaftet?“ – klingt dramatisch.", nicht_ru: "Не спрашивать «я арестован?» — звучит драматично.",
      detail: "fahrer-kontrolle-beendet",
      cop_de: "Bleiben Sie noch kurz im Auto.", cop_ru: "Останьтесь ещё немного в машине." }
  ],
  beifahrer: [
    {"k": "start", "de": "Anhalten", "ru": "Остановка", "ziel_de": "", "ziel_ru": "", "main": "s-start", "extra": ["s-video", "s-handy"], "tipp_de": "Sitzen bleiben, Hände sichtbar, langsam sprechen.", "tipp_ru": "Сидеть спокойно, руки на виду, говорить медленно.", "nicht_de": "Nicht ohne Vorwarnung in Taschen oder Rucksack greifen.", "nicht_ru": "Не лезть в карманы или рюкзак без предупреждения.", "detail": "aufnahme-nehmen-sie-auf", "cop_de": "Guten Tag, Polizei. Wir kontrollieren das Fahrzeug.", "cop_ru": "Добрый день, полиция. Мы проверяем автомобиль."},
    {"k": "ausweis", "de": "Ausweis", "ru": "Документ", "ziel_de": "", "ziel_ru": "", "main": "s-mitfahrer", "extra": ["s-personalien", "s-pass"], "tipp_de": "Besteht der Beamte darauf: Personalien unter Widerspruch nennen.", "tipp_ru": "Если настаивают — назвать данные, но с возражением.", "nicht_de": "Keinen falschen Namen nennen – falsche Personalien sind eine Ordnungswidrigkeit.", "nicht_ru": "Не называть чужое имя — ложные данные тоже нарушение.", "detail": "person-beifahrer-ausweis", "cop_de": "Vom Beifahrer brauche ich auch den Ausweis.", "cop_ru": "От пассажира тоже нужен документ."},
    {"k": "fragen", "de": "Fragen", "ru": "Вопросы", "ziel_de": "", "ziel_ru": "", "main": "s-zeuge", "extra": ["s-zursache"], "tipp_de": "Als Zeuge musst du bei der Polizei ohne Ladung der Staatsanwaltschaft nicht aussagen.", "tipp_ru": "Как свидетель ты не обязан давать показания в полиции без вызова от прокуратуры.", "nicht_de": "Nichts über den Fahrer erzählen, auch nicht „um zu helfen“.", "nicht_ru": "Ничего не рассказывать о водителе, даже «чтобы помочь».", "detail": "druck-zeuge-beifahrer", "cop_de": "Wo waren Sie beide heute Abend?", "cop_ru": "Где вы оба были сегодня вечером?"},
    {"k": "durchsuchung", "de": "Durchsuchung", "ru": "Обыск", "ziel_de": "", "ziel_ru": "", "main": "s-durchsuchung", "extra": ["s-grundlage", "s-handy-nein"], "tipp_de": "Hände sichtbar halten, nichts festhalten, nicht behindern.", "tipp_ru": "Руки на виду, ничего не держать, не мешать.", "nicht_de": "Taschen nicht selbst ausleeren – das kann wie eine Zustimmung wirken.", "nicht_ru": "Не выворачивать карманы самому — это может выглядеть как согласие.", "detail": "person-taschen-durchsuchen", "cop_de": "Leeren Sie mal Ihre Taschen aus.", "cop_ru": "Выверните, пожалуйста, карманы."},
    {"k": "massnahme", "de": "Zwang", "ru": "Принуждение", "ziel_de": "", "ziel_ru": "", "main": "s-widerspruch", "extra": ["s-wache"], "tipp_de": "Wache, Fotos, Fingerabdrücke: mit Worten widersprechen, nicht mit dem Körper.", "tipp_ru": "Участок, фото, отпечатки: возражать словами, не телом.", "nicht_de": "Nicht losreißen oder weglaufen – sonst droht zusätzlich ein Strafverfahren wegen Widerstands.", "nicht_ru": "Не вырываться и не убегать — иначе грозит ещё и уголовное дело за сопротивление.", "detail": "person-wache", "cop_de": "Sie kommen jetzt mit auf die Wache.", "cop_ru": "Сейчас вы поедете с нами в участок."},
    {"k": "ende", "de": "Ende", "ru": "Конец", "ziel_de": "", "ziel_ru": "", "main": "s-ende", "extra": ["s-festgehalten"], "tipp_de": "Nach der Kontrolle das Video mit „Jetzt sichern“ speichern.", "tipp_ru": "После проверки сохрани видео кнопкой «Jetzt sichern».", "nicht_de": "Nicht einfach weggehen, solange unklar ist, ob die Kontrolle vorbei ist.", "nicht_ru": "Не уходить просто так, пока не ясно, закончена ли проверка.", "detail": "person-weggehen", "cop_de": "Warten Sie hier.", "cop_ru": "Подождите здесь."}
  ],
  fuss: [
    {"k": "start", "de": "Anhalten", "ru": "Остановка", "ziel_de": "", "ziel_ru": "", "main": "s-start", "extra": ["s-video", "s-handy"], "tipp_de": "Stehen bleiben, Hände aus den Taschen, langsam sprechen.", "tipp_ru": "Остановиться, руки из карманов, говорить медленно.", "nicht_de": "Nicht ohne Vorwarnung in Taschen oder Rucksack greifen.", "nicht_ru": "Не лезть в карманы или рюкзак без предупреждения.", "detail": "aufnahme-nehmen-sie-auf", "cop_de": "Guten Tag, Polizei. Personenkontrolle.", "cop_ru": "Добрый день, полиция. Проверка документов."},
    {"k": "ausweis", "de": "Ausweis", "ru": "Документ", "ziel_de": "", "ziel_ru": "", "main": "s-personalien", "extra": ["s-pass"], "tipp_de": "Personalien nennen und den Ausweis zeigen, wenn du ihn dabeihast – mehr nicht.", "tipp_ru": "Назвать данные и показать документ, если он с собой, — больше ничего.", "nicht_de": "Nicht erklären, wohin und warum – das sind schon Angaben zur Sache.", "nicht_ru": "Не объяснять, куда и зачем идёшь, — это уже показания по делу.", "detail": "person-personalien", "cop_de": "Ihren Ausweis, bitte.", "cop_ru": "Ваш документ, пожалуйста."},
    {"k": "grund", "de": "Grund", "ru": "Причина", "ziel_de": "", "ziel_ru": "", "main": "s-grund", "extra": ["s-festgehalten"], "tipp_de": "Die Antwort des Beamten merken – das Video läuft.", "tipp_ru": "Запомни ответ полицейского — видео идёт.", "nicht_de": "Nicht darüber streiten, ob die Kontrolle fair ist.", "nicht_ru": "Не спорить, честная ли это проверка.", "detail": "person-grund", "cop_de": "Das ist eine ganz normale Kontrolle.", "cop_ru": "Это обычная проверка."},
    {"k": "durchsuchung", "de": "Durchsuchung", "ru": "Обыск", "ziel_de": "", "ziel_ru": "", "main": "s-durchsuchung", "extra": ["s-grundlage", "s-handy-nein"], "tipp_de": "Hände sichtbar halten, nichts festhalten, nicht behindern.", "tipp_ru": "Руки на виду, ничего не держать, не мешать.", "nicht_de": "Taschen nicht selbst ausleeren – das kann wie eine Zustimmung wirken.", "nicht_ru": "Не выворачивать карманы самому — это может выглядеть как согласие.", "detail": "person-taschen-durchsuchen", "cop_de": "Leeren Sie mal Ihre Taschen aus.", "cop_ru": "Выверните, пожалуйста, карманы."},
    {"k": "massnahme", "de": "Zwang", "ru": "Принуждение", "ziel_de": "", "ziel_ru": "", "main": "s-widerspruch", "extra": ["s-wache"], "tipp_de": "Wache, Fotos, Fingerabdrücke: mit Worten widersprechen, nicht mit dem Körper.", "tipp_ru": "Участок, фото, отпечатки: возражать словами, не телом.", "nicht_de": "Nicht losreißen oder weglaufen – sonst droht zusätzlich ein Strafverfahren wegen Widerstands.", "nicht_ru": "Не вырываться и не убегать — иначе грозит ещё и уголовное дело за сопротивление.", "detail": "person-wache", "cop_de": "Sie kommen jetzt mit auf die Wache.", "cop_ru": "Сейчас вы поедете с нами в участок."},
    {"k": "ende", "de": "Ende", "ru": "Конец", "ziel_de": "", "ziel_ru": "", "main": "s-ende", "extra": ["s-festgehalten"], "tipp_de": "Nach der Kontrolle das Video mit „Jetzt sichern“ speichern.", "tipp_ru": "После проверки сохрани видео кнопкой «Jetzt sichern».", "nicht_de": "Nicht einfach weggehen, solange unklar ist, ob die Kontrolle vorbei ist.", "nicht_ru": "Не уходить просто так, пока не ясно, закончена ли проверка.", "detail": "person-weggehen", "cop_de": "Bleiben Sie hier stehen.", "cop_ru": "Оставайтесь здесь."}
  ],
  rad: [
    {"k": "start", "de": "Anhalten", "ru": "Остановка", "ziel_de": "", "ziel_ru": "", "main": "s-start", "extra": ["s-video", "s-handy"], "tipp_de": "Anhalten, Hände sichtbar, langsam sprechen.", "tipp_ru": "Остановиться, руки на виду, говорить медленно.", "nicht_de": "Nicht ohne Vorwarnung in Taschen oder Rucksack greifen.", "nicht_ru": "Не лезть в карманы или рюкзак без предупреждения.", "detail": "aufnahme-nehmen-sie-auf", "cop_de": "Halt, Polizei! Steigen Sie mal ab.", "cop_ru": "Стоп, полиция! Слезьте с велосипеда."},
    {"k": "ausweis", "de": "Ausweis", "ru": "Документ", "ziel_de": "", "ziel_ru": "", "main": "s-personalien", "extra": ["s-rahmen"], "tipp_de": "Personalien nennen; die Rahmennummer zeigst du selbst.", "tipp_ru": "Назвать данные; номер рамы показываешь сам.", "nicht_de": "Nicht erklären, woher das Rad ist – einen Kaufbeleg musst du nicht dabeihaben.", "nicht_ru": "Не объяснять, откуда велосипед, — чек с собой носить не обязан.", "detail": "person-personalien", "cop_de": "Haben Sie einen Ausweis dabei?", "cop_ru": "У вас есть при себе документ?"},
    {"k": "fragen", "de": "Fragen", "ru": "Вопросы", "ziel_de": "", "ziel_ru": "", "main": "s-zursache", "extra": [], "tipp_de": "Zum Vorwurf (Gehweg, Licht, Handy) nichts sagen, nur Personalien.", "tipp_ru": "По поводу обвинения (тротуар, свет, телефон) молчать, только данные.", "nicht_de": "„Nur kurz“, „habe ich nicht gesehen“ – das sind schon Angaben zur Sache.", "nicht_ru": "«Я только на минутку», «не заметил» — это уже показания по делу.", "detail": "rad-regeln", "cop_de": "Warum fahren Sie auf dem Gehweg?", "cop_ru": "Почему вы едете по тротуару?"},
    {"k": "tests", "de": "Tests", "ru": "Тесты", "ziel_de": "", "ziel_ru": "", "main": "s-test", "extra": ["s-anordnung"], "tipp_de": "Besteht der Beamte darauf: fragen, ob es eine Anordnung ist.", "tipp_ru": "Если настаивают — спросить, распоряжение ли это.", "nicht_de": "Nicht zustimmen, „damit es schneller vorbei ist“.", "nicht_ru": "Не соглашаться «чтобы быстрее закончилось».", "detail": "fahrer-pusten", "cop_de": "Pusten Sie mal hier rein.", "cop_ru": "Подуйте сюда, пожалуйста."},
    {"k": "massnahme", "de": "Zwang", "ru": "Принуждение", "ziel_de": "", "ziel_ru": "", "main": "s-widerspruch", "extra": ["s-grundlage"], "tipp_de": "Blutprobe, Wache: mit Worten widersprechen, nicht mit dem Körper.", "tipp_ru": "Кровь, участок: возражать словами, не телом.", "nicht_de": "Nicht losreißen oder weglaufen – sonst droht zusätzlich ein Strafverfahren wegen Widerstands.", "nicht_ru": "Не вырываться и не убегать — иначе грозит ещё и уголовное дело за сопротивление.", "detail": "fahrer-blut", "cop_de": "Dann nehmen wir eben Blut.", "cop_ru": "Тогда возьмём кровь."},
    {"k": "ende", "de": "Ende", "ru": "Конец", "ziel_de": "", "ziel_ru": "", "main": "s-ende", "extra": ["s-unterschrift", "s-verwarnung"], "tipp_de": "Unterschreiben musst du nichts; eine Kopie darfst du mitnehmen.", "tipp_ru": "Подписывать ничего не обязан; копию можно взять.", "nicht_de": "Ein Verwarnungsgeld nicht aus Unsicherheit sofort annehmen.", "nicht_ru": "Не соглашаться на штраф сразу из неуверенности.", "detail": "fahrer-unterschrift", "cop_de": "Warten Sie noch kurz.", "cop_ru": "Подождите ещё немного."}
  ],
  immer: ["s-start", "s-zursache"]
};
